### ISSUE TITLE
[Sim] improve simulation

### ISSUE THREAD

**Issue by jsabsch** [dohamann/paparazzi#14]
e.g. randomize movements

**Comment by HerrSlavchev** [comment]
- Added alternative to the update rate control for the scene.  
  TODO:  
- randomized movements
- back-right-left collision avoidance

**Comment by HerrSlavchev** [comment]
Added walls in the room and an initial acceleration phase (movement in a given direction in order to test the PIDs).
Implemented x-y planar PID control.
